# Generated by Django 4.2.2 on 2023-07-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='static/img/usuario.png', upload_to='users'),
        ),
    ]
