# Generated by Django 4.2.2 on 2023-07-11 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0007_alter_user_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='genero',
        ),
    ]
