# Generated by Django 4.2.2 on 2023-07-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0009_user_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='static/img/usuario.png', upload_to='img'),
        ),
    ]
