# Generated by Django 4.2.2 on 2023-07-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0012_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='usuario.png', upload_to='media'),
        ),
    ]
