# Generated by Django 4.2.2 on 2023-07-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0013_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='solicitudFoto',
            field=models.ImageField(default=False, null=True, upload_to='media'),
        ),
    ]
